### ISSUE TITLE
No such property: license for class: Script1

### ISSUE THREAD

**Issue by Filecatdog** [barry-allen07/FB-Mod#1]
filebot -script fn:amc --output "/path/to/output" --action move -non-strict "/path/to/input" --log-file amc.log --def excludeList=amc.txt

```
No such property: license for class: Script1
groovy.lang.MissingPropertyException: No such property: license for class: Script1
        at Script1.run(Script1.groovy:14)
        at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:64)
        at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:74)
        at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:153)
        at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:36)
        at net.filebot.Main.main(Main.java:128)

Failure (°_°)
```

**Comment by torqueNoFriction** [comment]
Hello @ghost how did you end up fixing this ?

**Comment by barry-allen07** [comment]
Please see Scripts.md 

This issue has been fixed on the latest release.

Enjoy!

**Comment by Sada-Mio** [comment]
@barry-allen07 

replacing fn:amc to "https://raw.githubusercontent.com/barry-allen07/FB-Mod-Scripts/master/amc.groovy " allowed the script to work but output is no different than version 4.7.9 behavior

Input "Seishun Buta Yarou wa Bunny Girl Senpai no Yume o Minai" it gets recognized as the title "Buta" which is wrong. With the official 4.8.4 it correctly gets titled "Rascal Does Not Dream of Bunny Girl Senpai"

Other examples that fails, but works in official filebot v4.8.2

filebot -list --q "Yagate Kimi ni Naru" --db AniDB 
filebot -list --q "Irozuku Sekai no Ashita kara" --db AniDB

**Comment by barry-allen07** [comment]
@Sada-Mio This has been fixed on the latest release. I forgot to update the databases used by the software.

Enjoy it!

**Comment by Sada-Mio** [comment]
@barry-allen07 Thanks, script is working better now. 

But I get this warning which I don't understand

`WARNING: Module [filebot-format] - Unable to load extension class [org.apache.groovy.dateutil.extensions.DateUtilExtensions]
Nov 07, 2018 12:00:42 PM org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
WARNING: Module [filebot-format] - Unable to load extension class [org.apache.groovy.dateutil.extensions.DateUtilStaticExtensions]`

**Comment by torqueNoFriction** [comment]
@barry-allen07 where can we find the latest release ?

**Comment by Sada-Mio** [comment]
@torqueNoFriction https://github.com/barry-allen07/FB-Mod/releases

**Comment by barry-allen07** [comment]
@Sada-Mio The warning can be ignored for now. It's a known bug in one of the software libraries. It should not affect the functionality at all. 

Please let me know if this warning message is causing any problems.
