### ISSUE TITLE
deb package

### ISSUE THREAD

**Issue by vredesbyyrd** [barry-allen07/FB-Mod#2]
I stumbled on a post of yours linking to this repo. Any possibility you can upload a deb package, perhaps? 

Thanks for your time.

**Comment by barry-allen07** [comment]
Please check the releases tab.

Sorry for the delay (My schedule has been crazy lately).

Enjoy it!

**Comment by vredesbyyrd** [comment]
Downloaded :)  

No sweat regarding any delay. Your time is much appreciated!

Thanks again.
