### ISSUE TITLE
New release with Java 11 support?

### ISSUE THREAD

**Issue by d4k0** [barry-allen07/FB-Mod#3]
Hi,

Would it be possible to add a new release with Java 11 support? It was added to FileBot some weeks ago. The current version of this fork doesn't support Java 11 (it needs Java 10 and complains if it doesn't find it). Java 11 is a LTS release, so it will be the "main" version for some time (2 years?).

**Comment by barry-allen07** [comment]
I have been working on updating the app to the latest version (4.8.5) but the current version has some bugs at the moment. I`ve already added Java 11 support to the latest release. Would you prefer to wait until the current version gets sorted out? Or would you like me to update the previous version (4.8.2) with Java 11 support? 

Please let me know what would be best.

Regards.

barry-allen07

**Comment by d4k0** [comment]
Many thanks for your answer. The previous version with Java 11 support would be alright.

**Comment by barry-allen07** [comment]
> Many thanks for your answer. The previous version with Java 11 support would be alright.

Please check the latest release. I have updated the program to 4.8.5 (latest version) with Java 11 support.

Thanks for the feedback.
