### ISSUE TITLE
Filebot Subtitles Search Returns - Lookup By Hash Failed

### ISSUE THREAD

**Issue by sachatt** [barry-allen07/FB-Mod#4]
It seems like the subtitles search is broken.

For example if I run any script:
`filebot -script https://raw.githubusercontent.com/barry-allen07/FB-Mod-Scripts/master/amc.groovy --conflict override --action move -non-strict --log-file amc.log --output E:/ "D:\tmp\NAME.mkv" --def subtitles=en --log info`

It renames and moves the files, but the subtitles is not downloaded and I see the following error output:
`"Lookup by hash failed: The response could not be parsed."`

I am not sure how to fix this.

== Extra Notes ==

java -version
java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)

**Comment by barry-allen07** [comment]
Could you provide a sample file where this error is happening? Also did you login in to opensubtitles before running the script? 

Use this command to login:
filebot -script fn:configure

**Comment by sachatt** [comment]
The issue all of a sudden stopped happening :S Yes my login had been set correctly. Maybe a temporary issue on opensubtitles which got fixed.

However I noticed now that the -non-strict seems to not work. When I use the filebot app, it is able to find subtitles via non-strict method. However using the CLI just says file not found.

**Comment by barry-allen07** [comment]
lol what a silly mistake on my part

This has been fixed and -non-strict mode should work as normal. Give it another try.

Thanks for the bug report

Ps. I`ll leave the issue open until I get confirmation that it works appropriately.

**Comment by sachatt** [comment]
Is it possible to make a new release?

**Comment by sachatt** [comment]
I see it was an issue in the scripts which are now fixed :D Thank you very much for the great service, hats of to you !
