### ISSUE TITLE
Keylogger: App requests to log keystrokes from every application

### ISSUE THREAD

**Issue by michaelbryan92** [barry-allen07/FB-Mod#8]
is this intentional?

**Comment by parasiteoflife** [comment]
lol what a weak attempt

**Comment by barry-allen07** [comment]
There are no changes to the original code whatsoever besides removing the need for a license. This might be a false positive as this could be intended behavior by filebot. You are welcome to compare the code against the deleted filebot original repo:

https://github.com/deleted-repo/filebot
